.gitignore
README.md
src/main/kotlin/com/strumenta/kolasu/generation/JsonGenerator.kt
src/main/kotlin/com/strumenta/kolasu/generation/XmlGenerator.kt
src/main/kotlin/com/strumenta/kolasu/model/Model.kt
src/main/kotlin/com/strumenta/kolasu/model/Naming.kt
src/main/kotlin/com/strumenta/kolasu/model/Navigation.kt
src/main/kotlin/com/strumenta/kolasu/model/Position.kt
src/main/kotlin/com/strumenta/kolasu/model/Processing.kt
src/test/kotlin/com/strumenta/kolasu/model/PrintingTest.kt

Here are some suggestions to improve the documentation. I may not completely understand all functionality, so please correct mistakes.
There's also a random new unit test :-)

More documentation

---

src/main/kotlin/com/strumenta/kolasu/model/Processing.kt
src/main/kotlin/com/strumenta/kolasu/parsing/ParseTree.kt

If I understand the manual correctly, this is the way to go for collections in Kotlin.

Use more Kotlin-like collections

---

src/main/kotlin/com/strumenta/kolasu/generation/XmlGenerator.kt
src/main/kotlin/com/strumenta/kolasu/model/Navigation.kt
src/main/kotlin/com/strumenta/kolasu/model/Printing.kt
src/main/kotlin/com/strumenta/kolasu/model/Processing.kt
src/main/kotlin/com/strumenta/kolasu/parsing/Parsing.kt

Fix some warnings. Hopefully the changes are not upsetting.

Fixing warnings

---

src/main/kotlin/com/strumenta/kolasu/model/Processing.kt
src/test/kotlin/com/strumenta/kolasu/model/ProcessingTest.kt

Fixes #19. Maybe not a great solution, but better than a TODO :-)

Support only list

---

src/main/kotlin/com/strumenta/kolasu/generation/JsonGenerator.kt
src/main/kotlin/com/strumenta/kolasu/model/Navigation.kt
src/main/kotlin/com/strumenta/kolasu/model/Printing.kt
src/main/kotlin/com/strumenta/kolasu/model/Processing.kt
src/main/kotlin/com/strumenta/kolasu/model/Traversing.kt
src/test/kotlin/com/strumenta/kolasu/model/PrintingTest.kt
src/test/kotlin/com/strumenta/kolasu/model/ProcessingTest.kt

These are suggestions to make function names more expressive. I assume @ftomassetti is not going to agree with all of them, so let me know :-)

Some naming suggestions

---

src/main/kotlin/com/strumenta/kolasu/model/Processing.kt
src/test/kotlin/com/strumenta/kolasu/model/ProcessingTest.kt

I'm not sure the argument should be a list. Maybe a vararg. Not sure how this will be used in the future.

add replaceWithSeveral

---

src/main/kotlin/com/strumenta/kolasu/model/Processing.kt

I've kind of forgotten what it was I was still going to do, but I bet it all comes back if I just start with a simple thing like this suggested name change.
I'm kind of worried that no unit test was touched for this.

Suggested namechanges

---

core/src/main/kotlin/com/strumenta/kolasu/model/Position.kt

Introduce SyntheticSource

---

core/src/test/kotlin/com/strumenta/kolasu/model/ModelTest.kt
core/src/test/kotlin/com/strumenta/kolasu/serialization/JsonGenerationTest.kt

Adding tests to verify the problem cannot be reproduced at the moment

Duplicate properties issues

---

emf/src/main/kotlin/com/strumenta/kolasu/emf/Metamodel.kt
emf/src/test/kotlin/com/strumenta/kolasu/emf/KolasuMetamodelTest.kt
emf/src/test/kotlin/com/strumenta/kolasu/emf/MetamodelTest.kt

@loradd reviewing this is NOT urgent

Fix how generics are handled in EMF metamodel serialization (Kolasu 1.4)

---

emf/src/main/kotlin/com/strumenta/kolasu/emf/Model.kt
emf/src/main/kotlin/com/strumenta/kolasu/emf/kolasu_metamodel.kt
emf/src/test/kotlin/com/strumenta/kolasu/emf/MetamodelTest.kt
emf/src/test/kotlin/com/strumenta/kolasu/emf/ModelTest.kt
emf/src/test/kotlin/com/strumenta/kolasu/emf/cli/EMFCLIToolTest.kt

This solves the issue #99 reported by @alessiostalla .
It can also be relevant for @loradd

Handle ReferenceByName in EMF serialization

---

core/build.gradle
emf/build.gradle
javalib/build.gradle
playground/build.gradle

Signed-off-by: Lorenzo Addazi <lorenzo.addazi@strumenta.com>
Closes #104

[#104] Add Lorenzo to developers listed in the maven package

---

core/src/main/kotlin/com/strumenta/kolasu/model/Model.kt
emf/src/main/kotlin/com/strumenta/kolasu/emf/Model.kt
emf/src/main/kotlin/com/strumenta/kolasu/emf/kolasu_metamodel.kt
emf/src/test/kotlin/com/strumenta/kolasu/emf/ModelTest.kt
emf/src/test/kotlin/com/strumenta/kolasu/emf/cli/EMFCLIToolTest.kt

This PR is based on discussion https://github.com/Strumenta/StarLasu/discussions/5
This avoids touching `positionOverride` but focus only on the other, less controversial changes.
It includes update to EMF support

Updates to Origin and Destination

---

core/src/main/kotlin/com/strumenta/kolasu/transformation/Transformation.kt
core/src/test/kotlin/com/strumenta/kolasu/transformation/ASTTransformerTest.kt

Closes #147 
Signed-off-by: Lorenzo Addazi <lorenzo.addazi@strumenta.com>

ASTTransformer: post processing behavior

---

core/src/main/kotlin/com/strumenta/kolasu/transformation/Transformation.kt

Transformers: allow to opt out of setting children 

---

core/src/main/kotlin/com/strumenta/kolasu/model/Processing.kt
core/src/main/kotlin/com/strumenta/kolasu/model/Reflection.kt
core/src/test/kotlin/com/strumenta/kolasu/model/ProcessingTest.kt
core/src/test/kotlin/com/strumenta/kolasu/model/PropertyDescriptionTest.kt
javalib/src/test/java/com/strumenta/kolasu/javalib/CompilationUnit.java

Adding some reflection utils that appeared to be useful while working in an audit tool POC

Reflection utils

---

core/src/main/kotlin/com/strumenta/kolasu/parsing/KolasuParser.kt
core/src/main/kotlin/com/strumenta/kolasu/parsing/Parsing.kt

Expose ANTLR tokens in the default ANTLR-based lexer. 

---

core/src/main/kotlin/com/strumenta/kolasu/model/Processing.kt
core/src/test/kotlin/com/strumenta/kolasu/traversing/TraversingStructurallyTest.kt

This fixes a bug in the Node.nextSibling method

Fix bug in Node.nextSibling

---

emf/src/test/kotlin/com/strumenta/kolasu/emf/KolasuMetamodelTest.kt

Fix serialization of Serializable

---

core/src/main/kotlin/com/strumenta/kolasu/model/Range.kt

Consider source when comparing ranges. In order to do that we also make Sources comparable.
Fix #98

Consider source when comparing ranges

---

antlr/src/main/kotlin/com/strumenta/kolasu/antlr/parsing/ANTLRParseTreeUtils.kt

Introduce extension property for parseTreeNode

---

core/src/main/kotlin/com/strumenta/kolasu/model/CommonElements.kt
core/src/main/kotlin/com/strumenta/kolasu/model/Naming.kt
core/src/main/kotlin/com/strumenta/kolasu/model/Reflection.kt
core/src/main/kotlin/com/strumenta/kolasu/parsing/Parsing.kt
core/src/main/kotlin/com/strumenta/kolasu/serialization/JsonGenerator.kt
core/src/main/kotlin/com/strumenta/kolasu/serialization/XMLGenerator.kt
core/src/main/kotlin/com/strumenta/kolasu/symbolresolution/Testing.kt
core/src/main/kotlin/com/strumenta/kolasu/testing/Testing.kt
core/src/main/kotlin/com/strumenta/kolasu/validation/Result.kt
core/src/test/kotlin/com/strumenta/kolasu/model/ModelTest.kt
core/src/test/kotlin/com/strumenta/kolasu/symbolresolution/DeclarativeSymbolResolverTest.kt
emf/src/main/kotlin/com/strumenta/kolasu/emf/Model.kt
playground/src/main/kotlin/com/strumenta/kolasu/playground/PlaygroundExampleGenerator.kt

Fix #150 
Sorry to bother you @alessiostalla with one more PR, but I thought it makes sense to have you review this as this is related to an issue you opened

Renaming boolean properties using is prefix

---

build.gradle.kts
settings.gradle.kts

Adding support for Code Coverage
Fix #223

adding code coverage

---

playground/src/main/kotlin/com/strumenta/kolasu/playground/EMFSupport.kt
playground/src/main/kotlin/com/strumenta/kolasu/playground/TranspilationTrace.kt
playground/src/main/kotlin/com/strumenta/kolasu/playground/WorkspaceTranspilationTrace.kt
playground/src/test/kotlin/com/strumenta/kolasu/playground/TranspilationTraceTest.kt

This PR introduces the new Workspace Transpilation Trace, to represent transpilation of n files to m files and not just 1-to-1 transpilations

Workspace transpilation trace

---

core/src/main/kotlin/com/strumenta/kolasu/symbolresolution/Scoping.kt
core/src/test/kotlin/com/strumenta/kolasu/symbolresolution/ScopingTest.kt

Fixes #234 - Developers must be able to enable/disable case sensitivity for symbol resolution

---

core/build.gradle
core/src/main/kotlin/com/strumenta/kolasu/serialization/JsonGenerator.kt

JSON generator: use nodeType

---

core/src/main/kotlin/com/strumenta/kolasu/codegen/ASTCodeGenerator.kt
core/src/main/kotlin/com/strumenta/kolasu/language/KolasuLanguage.kt
core/src/test/kotlin/com/strumenta/kolasu/transformation/ASTTransformerTest.kt

ASTCodeGenerator: allow to customize the PrinterOutput.

---

lionweb-gen/src/main/kotlin/com/strumenta/kolasu/lionweb/ASTGenerator.kt

When generating AST classes make extended classes open

---

lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/LionWebModelConverter.kt
lionweb/src/test/kotlin/com/strumenta/kolasu/lionweb/LionWebModelConverterTest.kt

Considering parent when exporting tree to LionWeb

---

lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/BiMap.kt
lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/LionWebModelConverter.kt

Make LionWebModelConverter thread-safe

---

lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/LionWebLanguageConverter.kt
lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/LionWebModelConverter.kt
lionweb/src/test/kotlin/com/strumenta/kolasu/lionweb/LionWebLanguageConverterTest.kt
lionweb/src/test/kotlin/com/strumenta/kolasu/lionweb/LionWebModelConverterTest.kt

When exporting Kolasu enum values to LionWeb use Enumeration Literals

---

lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/LionWebLanguageConverter.kt
lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/StarLasuLWLanguage.kt

Serialize also CommonElement to LionWeb

---

core/src/main/kotlin/com/strumenta/kolasu/transformation/IdentityTransformation.kt
core/src/test/kotlin/com/strumenta/kolasu/transformation/ASTTransformerTest.kt

Adding origin to the identity mapping and a test to confirm it

fixing identity origin + adding test to check it
