src/main/kotlin/com/strumenta/kolasu/model/Navigation.kt, src/main/kotlin/com/strumenta/kolasu/model/Processing.kt, src/main/kotlin/com/strumenta/kolasu/model/Traversing.kt, src/test/kotlin/com/strumenta/kolasu/model/TraversingTest.kt
This is actually really, really powerful. I can do an in-place full tree transform like this:
```kotlin
project.descendants().forEach { node ->
when (node) {
is HexadecimalLiteralExpr -> {
val value = parseInt(node.rawValue.substring(1), 16)
node.replace(ConstantValueExpr(value, guessLiteralNumberType(value)))
}
}
}
```
=> Create a depth-first AST traversing sequence

src/main/kotlin/com/strumenta/kolasu/model/Processing.kt
In my opinion you always know if you want to transform in place or not when writing your code. So when I remove the boolean and make two separate methods for transformChildren, it becomes more readable and usable in my opinion. One getting/setting on the existing nodes, the other is creating new objects.
=> Split inplace/not inplace transform

src/main/kotlin/com/strumenta/kolasu/model/Printing.kt, src/test/kotlin/com/strumenta/kolasu/model/PrintingTest.kt
Quick PR: let the printer print private fields too. Fixes #10, but possibly not as desired.
=> Print private fields too.

src/main/kotlin/com/strumenta/kolasu/model/Processing.kt, src/test/kotlin/com/strumenta/kolasu/model/ProcessingTest.kt
This builds on #33, adding a few functions that make manipulation of lists of nodes complete as far as I can see.
There are sets of...
- functions that say "remove/addbefore/etc. THIS node" which use:
- functions that say "remove/addbefore/etc. the parameter node, which is somewhere in a list in THIS"
- functions that say "remove/addbefore/etc. the parameter item from THIS MutableList"
Possibly the second set of functions is redundant or confusing.
The function that looks for the node in all of the mutable lists in a node has been generalized.
=> Insert before after remove

core/src/main/kotlin/com/strumenta/kolasu/model/CommonElements.kt, emf/src/main/kotlin/com/strumenta/kolasu/emf/Metamodel.kt, emf/src/main/kotlin/com/strumenta/kolasu/emf/MetamodelBuilder.kt, emf/src/main/kotlin/com/strumenta/kolasu/emf/kolasu_metamodel.kt, emf/src/test/kotlin/com/strumenta/kolasu/emf/ModelTest.kt, emf/src/test/kotlin/com/strumenta/kolasu/emf/cli/EMFCLIToolTest.kt
For now, we introduce only Statement, Expression, and EntityDeclaration (for classes, interfaces, structs).
They are also added in the Kolasu metamodel.
=> Adding interfaces for common AST elements

core/src/main/kotlin/com/strumenta/kolasu/model/Model.kt, core/src/main/kotlin/com/strumenta/kolasu/model/Reflection.kt, emf/src/test/kotlin/com/strumenta/kolasu/emf/rpgast/data_definitions.kt
This implementation avoid the risk of stack overflow in case of nodes using links and presenting circular graphs.
The drawback is that the implementation must be final, otherwise the auto-generated toString of data classes prevail.
=> Implementing Node.toString

core/src/main/kotlin/com/strumenta/kolasu/codegen/ASTCodeGenerator.kt, core/src/main/kotlin/com/strumenta/kolasu/codegen/PrinterOutput.kt, core/src/main/kotlin/com/strumenta/kolasu/transformation/TrivialFactoryOfParseTreeToASTNodeFactory.kt, core/src/test/kotlin/com/strumenta/kolasu/codegen/ASTCodeGeneratorTest.kt, core/src/test/kotlin/com/strumenta/kolasu/codegen/KotlinPrinter.kt
Add a mechanism to override the behavior of an existing ASTCodeGenerator.
This is used for example to print special strings for node representing placeholders
=> Node printer overrider

core/src/main/kotlin/com/strumenta/kolasu/model/CommonElements.kt, core/src/main/kotlin/com/strumenta/kolasu/model/Processing.kt, core/src/main/kotlin/com/strumenta/kolasu/testing/testing.kt, core/src/test/kotlin/com/strumenta/kolasu/codegen/kotlinast.kt, emf/src/main/kotlin/com/strumenta/kolasu/emf/Metamodel.kt, emf/src/main/kotlin/com/strumenta/kolasu/emf/MetamodelBuilder.kt, emf/src/main/kotlin/com/strumenta/kolasu/emf/kolasu_metamodel.kt, emf/src/test/kotlin/com/strumenta/kolasu/emf/cli/EMFCLIToolTest.kt
Introducing QuotedElements. QuotedElement is used to represent elements in code templates and code matcher.
For example, in a code matcher: \`expr:v\` + 1, where \`expr:v\` is a QuotedElement, should match any code containing any expression added to 1.
In a code template \`expr:v\` + 1 indicates that, given expression `v` we want to sum it to 1.
=> Quoted element refinements

core/src/main/kotlin/com/strumenta/kolasu/transformation/TrivialFactoryOfParseTreeToASTNodeFactory.kt
ANTLR is generating two members for children of list types, one returning the whole list, the other just one child when provided an index.
We always need the full list with a single parameter, otherwise we get `Exception java.lang.IllegalArgumentException: Callable expects 2 arguments, but 1 were provided` when using `registerTrivialPTtoASTConversion`.
=> Fix method not found when of type list

core/src/main/kotlin/com/strumenta/kolasu/testing/testing.kt
=> AssertASTsAreEqual now does not crash when collections are null

core/src/main/kotlin/com/strumenta/kolasu/language/LanguageModule.kt, core/src/main/kotlin/com/strumenta/kolasu/model/Processing.kt, core/src/main/kotlin/com/strumenta/kolasu/parsing/KolasuParser.kt, core/src/test/kotlin/com/strumenta/kolasu/parsing/KolasuParserTest.kt, emf/src/main/kotlin/com/strumenta/kolasu/emf/EMFMetamodelSupport.kt, emf/src/main/kotlin/com/strumenta/kolasu/emf/cli/EMFCLICommands.kt, emf/src/main/kotlin/com/strumenta/kolasu/emf/cli/EMFCLITool.kt, emf/src/test/kotlin/com/strumenta/kolasu/emf/cli/EMFCLIToolTest.kt, playground/src/main/kotlin/com/strumenta/kolasu/playground/PlaygroundExampleGenerator.kt
These changes are required to make the RPG Lexer works, as it uses the RPGToken and not KolasuANTLRToken.
In my opinion this seems complicated, and we may consider adding the text field into KolasuToken, making it a concrete class. We could then make a method that given an ANTLR token convert it to a KolasuToken.
=> Make KolasuLexer parametric w.r.t. the type of token produced

core/src/main/kotlin/com/strumenta/kolasu/model/Model.kt, core/src/main/kotlin/com/strumenta/kolasu/model/Naming.kt, core/src/main/kotlin/com/strumenta/kolasu/model/Position.kt, core/src/main/kotlin/com/strumenta/kolasu/parsing/ANTLRParseTreeUtils.kt, core/src/main/kotlin/com/strumenta/kolasu/parsing/Parsing.kt, core/src/main/kotlin/com/strumenta/kolasu/symbolresolution/LocalSymbolResolver.kt
By making elements Serializable we can expose the parsers through RMI, as we do in the Audit Viewer
=> Add support for RMI

core/src/main/kotlin/com/strumenta/kolasu/mapping/ParseTreeToASTTransformer.kt, core/src/main/kotlin/com/strumenta/kolasu/transformation/TrivialFactoryOfParseTreeToASTNodeFactory.kt
Minor changes to the TrivialFactoryOfParseTreeToASTNodeFactory class, based on the work done in the Java language module.
Essentially:
* When we are waiting for a String or a String? we just get the text of the corresponding element, which could be not just a token but also a node such as IdentifierContext in the case of the Java language module
* When there is more than one constructor we pick the primary one, if available
=> TrivialFactoryOfParseTreeToASTNodeFactory refactoring

.gitignore, core/src/main/kotlin/com/strumenta/kolasu/mapping/ParseTreeToASTTransformer.kt, core/src/main/kotlin/com/strumenta/kolasu/parsing/ASTParser.kt, core/src/main/kotlin/com/strumenta/kolasu/parsing/KolasuParser.kt, core/src/test/kotlin/com/strumenta/kolasu/cli/CLITest.kt, core/src/test/kotlin/com/strumenta/kolasu/parsing/KolasuParserTest.kt, core/src/test/kotlin/com/strumenta/kolasu/transformation/ASTTransformerTest.kt, emf/src/test/kotlin/com/strumenta/kolasu/emf/cli/EMFCLIToolTest.kt
This implements issue #197 and modifies KolasuParser to correctly set the source according to the input.
However, this introduces an API change and parsers extending KolasuParser would need to be slightly modified.
=> ParseTreeToASTTransformer: option to set the source of each position/range

antlr/src/main/kotlin/com/strumenta/kolasu/antlr/Utils.kt, antlr/src/main/kotlin/com/strumenta/kolasu/antlr/parsing/ANTLRParseTreeUtils.kt, antlr/src/test/kotlin/com/strumenta/kolasu/antlr/model/OriginTest.kt, core/src/main/kotlin/com/strumenta/kolasu/codegen/PrinterOutput.kt, core/src/main/kotlin/com/strumenta/kolasu/model/Destinations.kt, core/src/main/kotlin/com/strumenta/kolasu/model/Model.kt, core/src/main/kotlin/com/strumenta/kolasu/model/Origins.kt, core/src/main/kotlin/com/strumenta/kolasu/transformation/Transformation.kt, core/src/test/kotlin/com/strumenta/kolasu/transformation/ASTTransformerTest.kt, emf/src/main/kotlin/com/strumenta/kolasu/emf/Model.kt, emf/src/test/kotlin/com/strumenta/kolasu/emf/ModelTest.kt, gradle.properties, playground/src/test/kotlin/com/strumenta/kolasu/playground/TranspilationTraceTest.kt
The node itself now contains exclusively the data but not the position or the source. They are part of the origin of the node.
The node has accessors to simplify getting access to them.
- rangeOverride is moved to the ParseTreeOrigin.
- detach is renamed in detachFromParseTree, because detach could be interpreted as "remove the node from the AST" (i.e., set its parent to null.
- destinations and origins are moved to separate files
- the Node is now not anymore an Origin or a Destination, both still it can be used almost as an Origin or a Destination by means of a few operators being added in Destinations.kt and overloaded methods such as `Node.withOrigin(Node)`
Fix #194
=> Reorganizing range, source, origin, and destinations

core/src/main/kotlin/com/strumenta/kolasu/mapping/support.kt
make translateCasted, translateList and translateOption work on ASTTtransformer
Fix #221
=> Move support extensions from ParseTreeToASTTransformer to ASTTtransformer

core/src/main/kotlin/com/strumenta/kolasu/transformation/Transformation.kt
This method has the purpose to indicate that something should not be translated directly. 
For example, if "b" appears in a grammar only within "a", and when translating "a" we also process all children of type "b", then we will never need to translate "b" directly. This is the often case for example for simple lists representing lists, like lists of parameters. In the method declarations we may process this list and possibly trigger the translation of the single parameters but not of the sub-rule defining the parameter lists.
This explicit "non-mapping" has two benefits:
1. Produce a better error message
2. Could be detected by a plugin used to check that we map all elements
=> Adding ASTTransformer.notTranslateDirectly

emf/src/main/kotlin/com/strumenta/kolasu/emf/Metamodel.kt, emf/src/main/kotlin/com/strumenta/kolasu/emf/MetamodelBuilder.kt, emf/src/test/kotlin/com/strumenta/kolasu/emf/MetamodelTest.kt
Without this change internal classes are considered to belong to a separate package. For example, a class Foo defined in a class a.b.Bar, will appear to belong to the package a.b.Bar. With this change it is recognized to belong to the package a.b, and it will have name Bar.Foo.
This is useful to generate documentation that looks like this:
=> Supporting the recognition of internal classes when mapping to EMF

core/src/main/kotlin/com/strumenta/kolasu/model/Model.kt
Addresses some issues that emerged during the development of our model repository:
- don't depend on reflection
- allow convenient usage with strings in addition to Attribute/Containment/Reference objects
Does not break API compatibility.
=> Improve the uniform API

core/src/main/kotlin/com/strumenta/kolasu/serialization/JsonDeserializer.kt, core/src/main/kotlin/com/strumenta/kolasu/serialization/JsonGenerator.kt, core/src/test/kotlin/com/strumenta/kolasu/serialization/JsonDeserializerTest.kt, core/src/test/kotlin/com/strumenta/kolasu/serialization/JsonGenerationTest.kt
I have an issue with serializing JSON with streaming for the RPG Parser. The issue is that when generating JSON with streaming there is essentially an alternative serialization process that is not affected by custom serializers and works a bit differently. This tentative fix effectively uses for the serialization with streaming the same methods for normal serialization.
I have also ensured that it is always used the `gsonBuilder` with the custom serializers.
However, I do not know if there was a specific reason for using alternative serialization methods for streaming serialization. Maybe I am missing something.
=> Tentative fix to deal with issues using generateJSONWithStreaming

core/src/main/kotlin/com/strumenta/kolasu/codegen/PrinterOutput.kt
This fixes https://github.com/Strumenta/kolasu/issues/267
=> PrinterOutput: don't wrap exceptions

lionweb-gen/src/main/kotlin/com/strumenta/kolasu/lionweb/ASTGenerator.kt
AST generation changes that check whether a class should be open and also fixes a bug when trying to refer to other generated class.
=> Fix AST classes generation from lionweb language.

core/src/main/kotlin/com/strumenta/kolasu/model/Position.kt, core/src/main/kotlin/com/strumenta/kolasu/parsing/Parsing.kt, core/src/main/kotlin/com/strumenta/kolasu/utils/Text.kt, core/src/test/kotlin/com/strumenta/kolasu/parsing/KolasuParserTest.kt
We do two things:
* We capitalize issues
* For issues that specify an issue on a token we specify the position for the issue to cover the whole token and not just the starting point of the token. Right now we specify "flat positions" (start == end), which means we cannot show those positions in editors
=> Improving parsing issues reporting

emf/src/main/kotlin/com/strumenta/kolasu/emf/MetamodelBuilder.kt, emf/src/main/kotlin/com/strumenta/kolasu/emf/MetamodelBuilding.kt, emf/src/main/kotlin/com/strumenta/kolasu/emf/cli/KolasuLanguageGeneratorCommand.kt, emf/src/test/kotlin/com/strumenta/kolasu/emf/MetamodelTest.kt
Fix #294
When exporting a Kolasu metamodel to Ecore permits to diffreentiate between the EPackage name and the package containing the Kotlin classes
=> Add parameter to the Ecore exporter

core/src/main/kotlin/com/strumenta/kolasu/language/KolasuLanguage.kt, core/src/main/kotlin/com/strumenta/kolasu/model/Model.kt, core/src/main/kotlin/com/strumenta/kolasu/model/Reflection.kt, core/src/test/kotlin/com/strumenta/kolasu/model/PropertyDescriptionTest.kt, core/src/test/kotlin/com/strumenta/kolasu/serialization/JsonGenerationTest.kt, javalib/src/test/java/com/strumenta/kolasu/javalib/CompilationUnit.java, lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/LionWebLanguageConverter.kt, lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/StarLasuLWLanguage.kt
* We add support for the Char type when converting to LionWeb
* When converting to LionWeb, we treat each type which is not a descendant of Node as a new Primitive type (note that it will require serializers and deserializers when converting ASTs to or from LionWeb)
* We support also derived properties as there was a case when `name` was marked as derived and it ended up being ignored
=> Fixes to support RPG Parser and LionWeb

core/src/main/kotlin/com/strumenta/kolasu/model/Processing.kt, core/src/test/kotlin/com/strumenta/kolasu/model/ProcessingTest.kt, gradle.properties, lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/BiMap.kt, lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/LionWebModelConverter.kt
Nodes which are "equals" but are not the same identity, cause issues when converting to LionWeb.
=> Avoid conflict in lion web conversion

lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/LionWebModelConverter.kt, lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/LionWebNodeIdProvider.kt, lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/SourceIdProvider.kt, lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/StructuralLionWebNodeIdProvider.kt, lionweb/src/test/kotlin/com/strumenta/kolasu/lionweb/StructuralLionWebNodeIdProviderTest.kt
We introduce an interface defining the logic used to produce LionWeb Node IDs for Kolasu Nodes.
This logic could be used to "predict" which ID will be associated to each node. We will also be able to recalculate that ID, if we have access to the instance of the LionWebNodeIdProvider. 
This is relevant for the Code Insight Studio and for the symbol resolution.
=> Introducing the LionWebNodeIdProvider

core/src/main/kotlin/com/strumenta/kolasu/ids/DeclarativeNodeIdProvider.kt, core/src/main/kotlin/com/strumenta/kolasu/ids/NodeIdProvider.kt, core/src/main/kotlin/com/strumenta/kolasu/ids/SourceIdProvider.kt, core/src/main/kotlin/com/strumenta/kolasu/ids/StructuralNodeIdProvider.kt, core/src/main/kotlin/com/strumenta/kolasu/language/KolasuLanguage.kt, lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/LionWebLanguageConverter.kt, lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/LionWebModelConverter.kt, lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/LionWebRootSource.kt, lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/StructuralLionWebNodeIdProvider.kt, lionweb/src/test/kotlin/com/strumenta/kolasu/lionweb/LionWebModelConverterTest.kt, lionweb/src/test/kotlin/com/strumenta/kolasu/lionweb/StructuralLionWebNodeIdProviderTest.kt, semantics/src/main/kotlin/com/strumenta/kolasu/semantics/symbol/provider/declarative/DeclarativeSymbolProvider.kt
When calculating the ID of a Node we may need to specify the coordinates in which the Node is going to be inserted. This is useful for example when defining a Node to be inserted within an existing tree in a LionWeb Repository. Locally the Node may not have a parent, but it will eventually get one and ID Logic may want to consider the ID of the parent that the Node is going to be attached to
=> ID Logic based on coordinates

gradle.properties, lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/LionWebModelConverter.kt, lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/StructuralLionWebNodeIdProvider.kt, lionweb/src/test/kotlin/com/strumenta/kolasu/lionweb/LionWebModelConverterTest.kt
We update to a new version of LionWeb Java and revise consequently support for serializing enum values.
We added a check from https://github.com/Strumenta/kolasu/pull/321, too.
=> Revise support for converting enum values to and from LionWeb

core/src/main/kotlin/com/strumenta/kolasu/transformation/Transformation.kt, emf/src/test/kotlin/com/strumenta/kolasu/emf/rpgast/DataDefinitions.kt
- Remove deprecated Mapped annotation
- Use `nodeType` instead of the class name (one less item of reflection)
- Avoid crashing with null collections (can happen in ANTLR sometimes)
- Fix `getChildNodeFactory` generic signature
=> Small AST transformer improvements

core/src/main/kotlin/com/strumenta/kolasu/codegen/ASTCodeGenerator.kt, core/src/main/kotlin/com/strumenta/kolasu/codegen/PrinterOutput.kt, core/src/main/kotlin/com/strumenta/kolasu/mapping/ParseTreeToASTTransformer.kt, core/src/main/kotlin/com/strumenta/kolasu/transformation/GenericNodes.kt, core/src/main/kotlin/com/strumenta/kolasu/transformation/Transformation.kt, core/src/test/kotlin/com/strumenta/kolasu/codegen/ASTCodeGeneratorTest.kt, core/src/test/kotlin/com/strumenta/kolasu/codegen/KotlinPrinter.kt, core/src/test/kotlin/com/strumenta/kolasu/transformation/ASTTransformerTest.kt
This PR is based on idea n° 3 in #352 by Federico:
- We keep track of the expected type of node of each child property.
- In case no AST transformer is registered for a given source type, we examine the expected node type of the property we're setting; if it's not abstract, we attempt to instantiate it, and fail with an exception if we can't.
- If we can instantiate it, we'll set it's "origin" to an instance of a class representing a failed translation, wrapping the normal origin. The code generator can recognize this and user code has a chance to provide a dedicated `NodePrinter` to handle such cases.
- For abstract node types, the user is expected to register a fallback `NodeFactory` and provide a placeholder node themselves. That could be of a specially designed subclass or a default …
=> #352 Support for "TODO" placeholder nodes for transpilers

lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/LionWebFluentInterface.kt, lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/LionWebModelConverter.kt, lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/StarLasuLWLanguage.kt, lionweb/src/test/kotlin/com/strumenta/kolasu/lionweb/LionWebModelConverterTest.kt
We represent placeholder nodes in Lionweb as regular nodes with:
- A _PlaceholderNode_ annotation on them
- Their origin set to the _PlaceholderNode_'s origin (could also be null).
Note that this only works for dynamic nodes (see https://github.com/LionWeb-io/lionweb-java/issues/153)
=> Support placeholder nodes in Lionweb too

core/src/main/kotlin/com/strumenta/kolasu/parsing/ASTParserInstantiator.kt, core/src/main/kotlin/com/strumenta/kolasu/parsing/KolasuParserInstantiator.kt, semantics/build.gradle.kts
Closes #359 - Adds an ASTParserInstantiator interface relaxing the constraints imposed by KolasuParserInstantiator
This PR introduces the following changes:
- Introduces an `ASTParserInstantiator` interface used to create `ASTParser` instances
- Modifies the existing `KolasuParserInstantiator` interface to extend the newly introduced one
=> Closes #359 - Adds an ASTParserInstantiator interface relaxing the constraints imposed by KolasuParserInstantiator

core/src/main/kotlin/com/strumenta/kolasu/language/KolasuLanguage.kt, core/src/main/kotlin/com/strumenta/kolasu/model/CommonElements.kt, core/src/main/kotlin/com/strumenta/kolasu/model/Reflection.kt, emf/src/main/kotlin/com/strumenta/kolasu/emf/MetamodelBuilder.kt, lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/LionWebFluentInterface.kt, lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/LionWebLanguageConverter.kt, lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/StarLasuLWLanguage.kt, lionweb/src/test/kotlin/com/strumenta/kolasu/lionweb/LionWebLanguageConverterTest.kt
Marker interfaces "worked" in Lionweb only because we were using Kolasu classes to deserialize the model and the metamodel. However, marker interfaces weren't being properly reflected in the serialized metamodel and would therefore be invisible to consumers of the metamodel that don't know the Kolasu node classes.
With this PR we fix that.
=> Properly support marker interfaces in Lionweb

emf/src/main/kotlin/com/strumenta/kolasu/emf/KolasuMetamodel.kt, emf/src/main/kotlin/com/strumenta/kolasu/emf/Metamodel.kt, emf/src/main/kotlin/com/strumenta/kolasu/emf/MetamodelBuilder.kt, emf/src/test/kotlin/com/strumenta/kolasu/emf/cli/EMFCLIToolTest.kt
Fix #367 
This is needed to be able to generate the EMF Metamodel for EGL, so that we can release it. We will then update the StarLasu Tools and CIS, then completing [#57 ](https://github.com/Strumenta/code-insight-studio/pull/57)
=> Add support in EMF for all new Marker Interfaces

core/src/main/kotlin/com/strumenta/kolasu/model/Position.kt, core/src/main/kotlin/com/strumenta/kolasu/parsing/KolasuParser.kt, core/src/main/kotlin/com/strumenta/kolasu/parsing/Parsing.kt, core/src/main/kotlin/com/strumenta/kolasu/testing/LexerTesting.kt
While working on Code Insight Studio I encountered the need to test the generation of tokens.
I therefore created a utility method that can check that a list of tokens cover the entire input, without overlaps. It can also check that the text corresponds exactly to the text in the original code at the given position.
In implementing this I added a few methods to work with text and positions.
I also added a few Token Categories.
=> Lexer testing

build.gradle, core/build.gradle, core/src/main/kotlin/com/strumenta/kolasu/codegen/PrinterOutput.kt, core/src/main/kotlin/com/strumenta/kolasu/ids/CachingNodeIDProvider.kt, core/src/main/kotlin/com/strumenta/kolasu/ids/SourceIdProvider.kt, core/src/main/kotlin/com/strumenta/kolasu/model/Errors.kt, core/src/main/kotlin/com/strumenta/kolasu/testing/Testing.kt, core/src/main/kotlin/com/strumenta/kolasu/transformation/DummyNodes.kt, core/src/main/kotlin/com/strumenta/kolasu/transformation/PlaceholderASTTransformation.kt, core/src/main/kotlin/com/strumenta/kolasu/transformation/Transformation.kt, core/src/test/kotlin/com/strumenta/kolasu/codegen/ASTCodeGeneratorTest.kt, core/src/test/kotlin/com/strumenta/kolasu/codegen/KotlinPrinter.kt, core/src/test/kotlin/com/strumenta/kolasu/ids/SourceIdProviderTest.kt, core/src/test/kotlin/com/strumenta/kolasu/mapping/ParseTreeToASTTransformerTest.kt, core/src/test/kotlin/com/strumenta/kolasu/transformation/DummyNodesTest.kt, gradle.properties, gradle/libs.versions.toml, lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/LionWebModelConverter.kt, lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/LionWebSource.kt, lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/StarLasuLWLanguage.kt, lionweb/src/test/kotlin/com/strumenta/kolasu/lionweb/LionWebModelConverterTest.kt, lionwebrepo-client/build.gradle.kts, lionwebrepo-client/src/main/kotlin/com/strumenta/kolasu/lionwebclient/KolasuClient.kt, playground/src/test/kotlin/com/strumenta/kolasu/playground/ParserTraceTest.kt, semantics/build.gradle.kts, semantics/src/main/kotlin/com/strumenta/kolasu/semantics/symbol/resolver/SymbolResolver.kt
When we implement transformers we may have the case in which the transformation is missing and the case in which it is failing. It may be failing because we cover a certain subset of cases. For example, when transforming from RPG to Java, we may cover a field declaration if the field is a string or a number, but not if it is of type pointer. In these cases we may want to still produce a partial transformation, treating the failure similarly to what we do with missing transformations. So expand the strategy for missing transformation to cover also failing transformations.
In addition to this:
* We ensure that generated IDs are compatible with LionWeb, removing illegal characters
* We expand the logic to instantiate a dummy node, with the sole purpose of attaching an origin to it. …
=> Fault tolerant transformers

core/src/main/kotlin/com/strumenta/kolasu/mapping/Support.kt, core/src/main/kotlin/com/strumenta/kolasu/transformation/Transformation.kt
There are circumstances in which we use the expected type to instantiate dummy nodes. For this to work we need to propagate the expected type in different circumstances.
=> Propagate expected type

core/src/main/kotlin/com/strumenta/kolasu/transformation/Transformation.kt, core/src/test/kotlin/com/strumenta/kolasu/transformation/ASTTransformerTest.kt
This will simplify the implementation of an intermediate model reusing parts of the original ast.
=> Introduce defaultTransformation and IDENTTITY_TRANSFORMATION

core/src/main/kotlin/com/strumenta/kolasu/transformation/IdentityTransformation.kt, core/src/main/kotlin/com/strumenta/kolasu/transformation/Transformation.kt, core/src/test/kotlin/com/strumenta/kolasu/transformation/ASTTransformerTest.kt
So far an identity transformation would keep the original node. The problem is that in this way we do not apply transformations to its descendants.
With this PR we change approach: the identity transformation makes a copy of the node, applying transformations to che children. In this way we can define a few transformations and transform only certain nodes, while keeping other nodes as in the original AST (besides their children being transformed).
=> Bugfix for identity transformation

core/src/main/kotlin/com/strumenta/kolasu/model/Model.kt
We should not try to print also derived properties as they could lead to redundant information being printed, and possible circular structures (leading to stack overflows).
=> Consider only original properties in Node.toString

codebase/build.gradle.kts, codebase/src/main/kotlin/com/strumenta/kolasu/codebase/CodebaseAdapters.kt, core/build.gradle, emf/build.gradle, gradle/libs.versions.toml, lionweb-gen-gradle/build.gradle.kts, lionweb-gen/build.gradle, lionweb/build.gradle, lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/LionWebModelConverter.kt, lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/PrimitiveSerialization.kt, lionwebrepo-client/build.gradle.kts, lionwebrepo-client/src/functionalTest/kotlin/com/strumenta/kolasu/lionwebclient/TodoFunctionalTest.kt, lionwebrepo-client/src/main/kotlin/com/strumenta/kolasu/lionwebclient/KolasuClient.kt, playground/build.gradle
As part of this PR we do minor maintenance operations:
- We update the version of gson used and adopt the version catalog for managing such version
- We update the versions of LW Java, LW Kotlin,  StarLasu Specs
- We add the parameter jsonSerialization to convertCodebase
- We expose the serializers and deserializers for the StarLasuLWLanguage (a.k.a. ASTLanguage), so that they can be used individually from users of Kolasu
- We update TodoFunctionalTest to create a separate repository for each test. This is necessary because now the base class AbstractRepoClientFunctionalTest does not recreate the whole DB for each test
- In KolasuClient we do not keep a separate JsonSerialization, but we use the one of the wrapped LionWebClient
Depends on …
=> Update LionWeb dependencies

codebase/src/main/kotlin/com/strumenta/kolasu/codebase/CodebaseAdapters.kt, codebase/src/main/kotlin/com/strumenta/kolasu/codebase/CodebaseFile.kt, codebase/src/main/kotlin/com/strumenta/kolasu/codebase/FileBasedCodebase.kt, core/src/main/kotlin/com/strumenta/kolasu/model/Model.kt, core/src/main/kotlin/com/strumenta/kolasu/model/Properties.kt, gradle/libs.versions.toml, javalib/src/test/java/com/strumenta/kolasu/javalib/CompilationUnit.java, lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/LionWebModelConverter.kt, lionweb/src/main/kotlin/com/strumenta/kolasu/lionweb/PrimitiveSerialization.kt
Fixing minor issues emerged while serializing to LionWeb.
* We update the Starlasu Specs to 0.2.1
* We ensure that when calculating the original properties we do not first calculate all properties (including derived properties) to later filter them out. This is important as calculation of derived properties could fail while we are building the node
* We correct support for serializing and deserializing null values for primitive types
=> Fix serialization
